(define-module (maak)
  #:use-module (guix build utils)
  #:use-module (maak dsl)
  #:use-module (ice-9 threads)
  #:use-module (uraj maak guix)
  #:use-module (uraj maak process)
  #:use-module (uraj utils file path)
  #:re-export (guix)
  #:export (update-channels-lock compile-guix))

(define (update-channels-lock)
  (let ((tmp-output-filename (guix-env-path "channels-lock.scm.tmp")))
    (run-command (list "guix" "time-machine"
                       (string-append "--channels=" (guix-env-path "channels.scm"))
                       "--" "describe" "-f" "channels")
                 #:output-file tmp-output-filename)
    (unless (dry-run?)
      (rename-file tmp-output-filename (guix-env-path "channels-lock.scm")))))

(define (compile-guix)
  (run-command '("git" "submodule" "update" "--init"))
  (with-directory-excursion (guix-env-path "channels/guix")
    (unless (file-exists? "Makefile")
      (run-command '("./bootstrap"))
      (run-command '("./configure")))
    (run-command `("make" "-j" ,(number->string (current-processor-count))))))
